language: c
dist: bionic

matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
    - os: osx
      osx_image: xcode12
    - os: osx
      osx_image: xcode9.4

before_install:
    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo apt-get update;
        sudo apt -q install fpc;
        sudo apt -q install libprimesieve-dev;
        fpc -B -Cn -dUSE_ABI6 primesieve_info.pas;
        cat link.res;
        fpc -va -B -dUSE_ABI6 -O3 -CX -XX -Fl/usr/local/lib primesieve_info.pas;
        fpc -vh -B -O3 -CX -XX -dUSE_ABI6 -Fl/usr/local/lib examples/prev_prime.pas;
        fpc -vh -B -O3 -CX -XX -dUSE_ABI6 -Fl/usr/local/lib examples/primesieve_iterator.pas;
        fpc -vh -B -O3 -CX -XX -dUSE_ABI6 -Fl/usr/local/lib examples/totient.pas;
        fpc -vh -B -O3 -CX -XX -dUSE_ABI6 -Fl/usr/local/lib mult/mult_cli/mult_cli.pas -Fumult/;
        cc primesieve_info.c -o primesieve_info_c -lprimesieve;
      elif [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
        brew install primesieve;
        export DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH:/usr/local/lib;
        export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH:/usr/local/lib;
        sudo update_dyld_shared_cache;
        echo $DYLD_LIBRARY_PATH;
        echo $LD_LIBRARY_PATH;
        echo $DYLD_FALLBACK_LIBRARY_PATH;
        fpc -B -Cn primesieve_info.pas;
        cat link.res;
        fpc -va -B -O3 -CX -XX -Fl/usr/local/lib primesieve_info.pas;
        fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/prev_prime.pas;
        fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/primesieve_iterator.pas;
        fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/totient.pas;
        fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib mult/mult_cli/mult_cli.pas -Fumult/;        
        cc primesieve_info.c -o primesieve_info_c -lprimesieve;
      fi

install:
  - fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/count_primes.pas
  - fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/nth_prime.pas
  - fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/store_primes_in_array.pas
  - fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/printlets.pas
  - fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/countlets.pas

script:
  - ./primesieve_info
  - ./primesieve_info_c
  - examples/count_primes > examples/count_primes.fpc.out
  - diff -w examples/count_primes.fpc.out examples/count_primes_c.out
  - diff -w examples/count_primes.dcc64.out examples/count_primes_c.out
  - examples/nth_prime > examples/nth_prime.fpc.out
  - diff -w examples/nth_prime.fpc.out examples/nth_prime_c.out
  - diff -w examples/nth_prime.dcc64.out examples/nth_prime_c.out
  - examples/store_primes_in_array > examples/store_primes_in_array.fpc.out
  - diff -w examples/store_primes_in_array.fpc.out examples/store_primes_in_array_c.out
  - diff -w examples/store_primes_in_array.dcc64.out examples/store_primes_in_array_c.out
  - examples/prev_prime > examples/prev_prime.fpc.out
  - diff -w examples/prev_prime.fpc.out examples/prev_prime_c.out
  - diff -w examples/prev_prime.dcc64.out examples/prev_prime_c.out
  - examples/primesieve_iterator > examples/primesieve_iterator.fpc.out
  - diff -w examples/primesieve_iterator.fpc.out examples/primesieve_iterator_c.out
  - diff -w examples/primesieve_iterator.dcc64.out examples/primesieve_iterator_c.out
  - time examples/printlets 6 0 1000000
  - time examples/countlets 6 0 1000000000
  - examples/totient 1 69
  - examples/totient 1 100000 > examples/totient.fpc.out
  - diff -w examples/totient.fpc.out examples/b000010.txt
  - mult/mult_cli/mult_cli 10 1 100000 > mult/oeis/totient.fpc.out
  - diff -w mult/oeis/totient.fpc.out mult/oeis/b000010.txt
  - mult/mult_cli/mult_cli 8683 1 100000 > mult/oeis/moebius.fpc.out
  - diff -w mult/oeis/moebius.fpc.out mult/oeis/b008683.txt
  - mult/mult_cli/mult_cli 5 1 100000 > mult/oeis/tau.fpc.out
  - diff -w mult/oeis/tau.fpc.out mult/oeis/b000005.txt
