language: c
dist: bionic

os:
  - linux
  - osx

osx_image: xcode12

before_install:
    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo apt-get update;
        sudo apt -q install fpc;
        sudo apt -q install libprimesieve-dev;
      elif [[ $TRAVIS_OS_NAME == osx ]]; then 
        brew update > /dev/null;
        brew install fpc > /dev/null;
        brew install primesieve;
        export DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH:/usr/local/lib;
        export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH:/usr/local/lib;        
        sudo update_dyld_shared_cache;
        echo $DYLD_LIBRARY_PATH;
        echo $LD_LIBRARY_PATH;        
        echo $DYLD_FALLBACK_LIBRARY_PATH;                
      fi

install:
  - fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib primesieve_info.pas
  - fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/count_primes.pas
  - fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/nth_prime.pas  
  - fpc -vh -B -O3 -CX -XX -Fl/usr/local/lib examples/store_primes_in_array.pas  
  
script:
  - ./primesieve_info
  - examples/count_primes
  - examples/nth_prime  
  - examples/store_primes_in_array  
