language: c
dist: bionic

os:
  - linux
  - osx
  - windows

before_install:
    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo apt-get update;
        sudo apt -q install fpc;
        sudo apt -q install libprimesieve-dev;
      elif [[ $TRAVIS_OS_NAME == osx ]]; then 
        brew update > /dev/null;
        brew install fpc > /dev/null;
        brew install primesieve;
        export DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH:/usr/local/lib;
        echo $DYLD_LIBRARY_PATH;
        sudo update_dyld_shared_cache;
      else
        choco install freepascal;
        choco install mingw;
        cmd.exe //c "RefreshEnv.cmd"; 
        export PATH=$PATH:/C/lazarus/fpc/3.0.4/bin/x86_64-win64;
        ls /C/lazarus/fpc/3.0.4/bin;
        ls /C/lazarus/fpc/3.0.4/bin/x86_64-win64;         
      fi

install:
  
script:
  - cd libprimesieve
  - fpc -B -vh -O3 -CX -XX ../primesieve_info.pas
  - ../primesieve_info
  - fpc -B -vh -Fu../ -O3 -CX -XX ../examples/count_primes.pas
  - fpc -B -vh -Fu../ -O3 -CX -XX ../examples/nth_prime.pas  
  - fpc -B -vh -Fu../ -O3 -CX -XX ../examples/store_primes_in_array.pas  
  - ../examples/count_primes
  - ../examples/nth_prime  
  - ../examples/store_primes_in_array  
