language: c
dist: bionic

os:
  - linux
  - osx

osx_image: xcode12

before_install:
    - if [[ $TRAVIS_OS_NAME == linux ]]; then
        sudo apt-get update;
        sudo apt -q install fpc;
        sudo apt -q install libprimesieve-dev;
      elif [[ $TRAVIS_OS_NAME == osx ]]; then 
        brew update > /dev/null;
        brew install fpc > /dev/null;
        brew install primesieve;
        export DYLD_LIBRARY_PATH=.:$DYLD_LIBRARY_PATH:/usr/local/lib;
        echo $DYLD_LIBRARY_PATH;
        sudo update_dyld_shared_cache;
      fi

install:
  
script:
  - fpc -vh -B -O3 -CX -XX primesieve_info.pas
  - ./primesieve_info
  - cd examples
  - fpc -vh -B -Fu../ -O3 -CX -XX count_primes.pas
  - fpc -vh -B -Fu../ -O3 -CX -XX nth_prime.pas  
  - fpc -vh -B -Fu../ -O3 -CX -XX -dUSE_ABI6 prev_prime.pas
  - fpc -vh -B -Fu../ -O3 -CX -XX -dUSE_ABI6 primesieve_iterator.pas
  - fpc -vh -B -Fu../ -O3 -CX -XX store_primes_in_array.pas  
  - ./count_primes
  - ./nth_prime  
  - ./prev_prime
  - ./primesieve_iterator
  - ./store_primes_in_array  
